### ISSUE TITLE
bug or not?

### ISSUE THREAD

**Issue by webtotma** [kizza/CSS-Less-ish#8]
Hi!

Take the example

```
/*@link = #6699CC*/  
a { color: @link}

```

produces

```
/*@link = #6699CC*/  
a { color: #6699CC*/}

/* Variables:link{33:42} */
```
a { color: #6699CC*/} -> */ after color

When multi-line comments it works fine.

Thanks for the cool plugin!

**Comment by kizza** [comment]
Wow, totally a bug (and one that's in the documentation!) - thanks for letting me know @webtotma!  I've just pushed a new release to GitHub which fixes it (sublime package control should push the new version soon).  Thanks again - and very humbled to hear that you like the plugin - gracias!
